module.exports = {
  apps: [
    {
      name: "iq-home-api",
      script: "./bin/api",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        HTTP_ADDR:                 "0.0.0.0:9001",
        DATABASE_URL:              "postgresql://postgres:password@localhost:5432/postgres",
        INTERNAL_TOKEN:            "change-me",
        ADMIN_USERNAME:            "admin",
        ADMIN_PASSWORD:            "change-me",
        SUPABASE_URL:              "https://your-project.supabase.co",
        SUPABASE_SERVICE_ROLE_KEY: "your-service-role-key",
        OPENAI_BASE_URL:           "https://api.openai.com",
        OPENAI_API_KEY:            "sk-...",
        OPENAI_MODEL:              "gpt-4o-mini",
        OPENAI_VISION_MODEL:       "gpt-4o-mini",
        OPENAI_TRANSCRIBE_MODEL:   "gpt-4o-mini-transcribe",
        OPENAI_EMBEDDING_MODEL:    "text-embedding-3-large",
        TIKA_URL:                  "http://127.0.0.1:9998",
        TELEGRAM_BASE_URL:         "https://api.telegram.org",
        TELEGRAM_BOT_TOKEN:        "",
        TELEGRAM_WEBHOOK_SECRET:   "",
        MANAGER_CHAT_ID:           "",
        DIRECTOR_CHAT_ID:          "",
        CORS_ALLOW_ORIGIN:         "*",
        PRODUCT_URL:               "https://your-domain.kz/products/",
        PAYMENT_BASE_URL:          "",
      },
    },
  ],
};
